export const GET_PRODUCTS = "PRODUCT/GET_PRODUCT";
export const GET_PRODUCTS_SUCCESS = "PRODUCT/GET_PRODUCT_SUCCESS";
export const GET_PRODUCTS_ERROR = "PRODUCT/GET_PRODUCT_ERROR";

export const GET_SELLING_PRODUCTS = "PRODUCT/GET_SELLING_PRODUCTS";
export const GET_SELLING_PRODUCTS_SUCCESS = "PRODUCT/GET_SELLING_PRODUCTS_SUCCESS";
export const GET_SELLING_PRODUCTS_ERROR = "PRODUCT/GET_SELLING_PRODUCTS_ERROR";

export const GET_HOT_PRODUCTS = "PRODUCT/GET_HOT_PRODUCTS";
export const GET_HOT_PRODUCTS_SUCCESS = "PRODUCT/GET_HOT_PRODUCTS_SUCCESS";
export const GET_HOT_PRODUCTS_ERROR = "PRODUCT/GET_HOT_PRODUCTS_ERROR";


export const POST_ORDER = "PRODUCT/POST_ORDER";
export const POST_ORDER_SUCCESS = "PRODUCT/POST_ORDER_SUCCESS";
export const POST_ORDER_ERROR = "PRODUCT/POST_ORDER_ERROR";